### ISSUE TITLE
fog-dnsimple's executable "console" conflicts with fir-cli

### ISSUE THREAD

**Issue by Coeur** [fog/fog-dnsimple#2]
```
Updating fog
Fetching: fog-core-1.45.0.gem (100%)
Successfully installed fog-core-1.45.0
Fetching: fog-digitalocean-0.3.0.gem (100%)
Successfully installed fog-digitalocean-0.3.0
fog-dnsimple's executable "console" conflicts with fir-cli
Overwrite the executable? [yN]  n
ERROR:  Error installing fog:
	"console" from fog-dnsimple conflicts with installed executable from fir-cli
```

What is the recommendation to solve this?
fir-cli is from https://github.com/FIRHQ/fir-cli

**Comment by Coeur** [comment]
Could you maybe rename it to `fog-console`?

**Comment by geemus** [comment]
or maybe fog-dnsimple?

@weppos thoughts?

**Comment by weppos** [comment]
I'm currently on vacation for a week, with limited connectivity.
I'll check once I'll be back.

-- Simone

**Comment by geemus** [comment]
No worries, enjoy the vacation!

**Comment by weppos** [comment]
I was researching this issue, and I admit I am confused.

There is indeed a console file in this repo, but it's not configured to be downloaded or installed as it's a local script.

The executables are in the `exe` folder: (which BTW seems to be the new bundler default when you use `bundle gem <foo>`)
https://github.com/fog/fog-dnsimple/blob/master/fog-dnsimple.gemspec#L20

Instead, the `fir-cli` actually publishes all the binaries (that in fact may cause conflicts with potentially any other gem)
https://github.com/FIRHQ/fir-cli/blob/master/fir-cli.gemspec#L18

I'm not really sure this is an issue of this repository, to be honest.

**Comment by plribeiro3000** [comment]
It took me a while to get to respond here. @weppos is correct.

This is not an issue of this repo. `fir-cli` needs to be updated accordingly.

Closing since there isn't anything to be done here.

**Comment by Coeur** [comment]
@plribeiro3000 thank you for responding. Actually, **fir-cli** has an open ticket for just as long as you, and they haven't replied yet, ah ah! https://github.com/FIRHQ/fir-cli/issues/159

**Comment by plribeiro3000** [comment]
@Coeur Maybe we can send a PR? It looks like a simple change. 😉
